### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by franklapua** [webfp/tor-browser-selenium#113] opened 2019-04-18 14:30 UTC
I rebuilt my project from a local machine to a cloud-based machine.  Same version of Ubuntu (18.04) but now I get the "connection refused" error. I have included what I think is relevant below.  If you need more, please feel free to ask.

TBB version : {"version":"8.0.8","architecture":"linux64","channel":"release","locale":"en-US"}
geckodriver version: geckodriver 0.24.0 ( 2019-01-28)

Error:
Traceback (most recent call last):
  File "headless.py", line 41, in <module>
    main()
  File "headless.py", line 37, in main
    headless_visit(tbb_path)
  File "headless.py", line 21, in headless_visit
    with TorBrowserDriver(tbb_dir) as driver:
  File "/usr/local/lib/python2.7/dist-packages/tbselenium/tbdriver.py", line 57, in __init__
    log_path=tbb_logfile_path)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

[geckodriver.log](https://github.com/webfp/tor-browser-selenium/files/3094822/geckodriver.log)

**Comment by jonathanng** [comment] 2019-04-18 20:29
I'm getting a similar error in my log file as well:

> Authentication failed: Password did not match HashedControlPassword *or* authentication cookie.

**Comment by franklapua** [comment] 2019-04-18 21:33
@jonathanng I had that error too in a previous iteration. What fixed it for me was rehashing the tor control password, adding it back to torrc, and restarting the tor service.   Sorry I can't be of more help on that one.

**Comment by gunesacar** [comment] 2019-04-19 00:28
@franklapua Thanks for the report. Can you try running Firefox on the same system?

Are you using `Xvfb`, `pyvirtualdisplay` or similar when running on cloud?

**Comment by franklapua** [comment] 2019-05-08 16:28
Sorry for the delay, I have been trying to do as you suggested and use Firefox, but I'm not sure I am doing that correctly.  Any help would be appreciated.  Yes, I am using Xvfb and pyvirtualdisplay. 
I've attached the sample code I am using to test.  

Usage:
python headless.py http://check.torproject.org 

[headless.py.txt](https://github.com/webfp/tor-browser-selenium/files/3158343/headless.py.txt)

**Comment by gunesacar** [comment] 2019-09-05 11:07
The code you shared immediately closes the xvfb display (line 32), you need to move `stop_xvfb` call to the end of `headless_visit`
- `str(url)` returns invalid filename, so the screenshot will not be saved. You may instead use something like `url.split("://")[-1]` or follow [this solution](https://stackoverflow.com/questions/7406102/create-sane-safe-filename-from-any-unsafe-string)

Closing since the problem is not related to the library.

**Closed by gunesacar** 2019-09-05 11:07 UTC
